
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SALAMA HAMIDAN
 */
public class HMS extends javax.swing.JFrame {

    static void writeError() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static void set_RoomNo(String inputRoomNo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static void set_RoomCategory(String inputRoomCategory) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static void setHMS_RoomNo(String inputRoomNo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static void setHMS_RoomCategory(String inputRoomCategory) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static void setHMS_PRICE(String inputPRICE) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static String getHMS_RoomCategory() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static String getHMS_RoomNo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static String getHMS_PRICE() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    private Object lblDisplay;

    /**
     * Creates new form HMS
     */
    public HMS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHMS = new javax.swing.JLabel();
        lblphoto = new javax.swing.JLabel();
        lblRN = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        lblRC = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblP = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        txtOC = new javax.swing.JTextField();
        btnS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHMS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHMS.setForeground(new java.awt.Color(255, 153, 153));
        lblHMS.setText("HOSTEL MANAGEMENT SYSTEM");

        lblphoto.setText("click to upload");

        lblRN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRN.setText("Room No. :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select room no", "room 1", "room 2", "room 3", "room 4", "room 5", "room 6", "room 7", "room 8", "room 9", "room 10", " ", " ", " " }));

        lblRC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRC.setText("Room Category :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select hostel type", "SOUTH AFRICA", "BURJ KHALIFA", "GHANA", "JORDAN", "RIYAD", " ", " ", " " }));

        lblP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblP.setText("PRICE :");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "prices", "$100 per semester", "$240 per semester", "$450 per semester", "$500 per semester", "$650 per semester", " ", " " }));

        btnS.setText("SUBMIT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtOC, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblHMS, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnS))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHMS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(txtOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     String inputRoomNo, inputRoomCategory, inputPRICE;
       private void btnSActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        inputRoomNo = lblRN.getText();
        HMS.setHMS_RoomNo(inputRoomNo);
        inputRoomCategory = lblRC.getText();
        HMS.setHMS_RoomCategory(inputRoomCategory);
        inputPRICE = lblP.getText();
        HMS.setHMS_PRICE(inputPRICE); 
        lblphoto.setText(HMS.getHMS_PRICE()+" " +HMS.getHMS_RoomNo() +" " +HMS.getHMS_RoomCategory()+" "+" Added!!!");
        
       private void lblPhotoMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
       JFileChooser myChooser = new JFileChooser();
       myChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
       int result = myChooser.showOpenDialog(myChooser);
       if(result == JFileChooser.APPROVE_OPTION)
       {
           lblPhoto.setText("");
           File myFile = myChooser.getSelectedFile();
           String filePath = myFile.toString();
           System.out.println(filePath);
           Icon myIcon;
           myIcon =  new ImageIcon(new ImageIcon(filePath).getImage().getScaledInstance(80, 100, java.awt.Image.SCALE_SMOOTH));
           lblPhoto.setIcon(myIcon);
           
           new File ("C:\\StudentProfile").mkdir();
           Path source = Paths.get(filePath);
           Path targetDir = Paths.get("C:\\StudentProfile");
           Path target = targetDir.resolve(myChooser.getSelectedFile().getName());
           
           System.out.print(target.toString());
           try{
               Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING);
           }catch(Exception e)
           {
               System.out.println(e.getMessage());
           }
           
       }
       
       //System.out.println("Mouse Clicked....");
    }                                     

    private void lblPhotoMouseEntered(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        System.out.println("Mouse Entered...");
               
       
       
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnS;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel lblHMS;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblRC;
    private javax.swing.JLabel lblRN;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JTextField txtOC;
    // End of variables declaration//GEN-END:variables

    private static class lblPhoto {

        private static void setText(String string) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private static void setIcon(Icon myIcon) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public lblPhoto() {
        }
    }
}
